
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 19 17:55:41 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 24;
  public static final int READ = 14;
  public static final int IDENT = 28;
  public static final int PLUS = 20;
  public static final int RBRACE = 4;
  public static final int RPAREN = 12;
  public static final int EQUAL = 8;
  public static final int CHAR = 31;
  public static final int SEMI = 5;
  public static final int RETURN = 13;
  public static final int COLON = 27;
  public static final int LBRACKET = 9;
  public static final int LPAREN = 11;
  public static final int LBRACE = 3;
  public static final int RBRACKET = 10;
  public static final int INC = 17;
  public static final int COMMA = 6;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int DIV = 23;
  public static final int PROG = 2;
  public static final int DEC = 18;
  public static final int UNION = 16;
  public static final int MINUS = 21;
  public static final int DOT = 26;
  public static final int CONST = 7;
  public static final int PRINT = 15;
  public static final int error = 1;
  public static final int NEW = 25;
  public static final int BOOL = 30;
  public static final int MUL = 22;
  public static final int VOID = 19;
}

